# Site settings
title: Vinícius Feitosa da Silva
description: DevPage
owner: PHPDF
url: "https://viniciusfesil.com.br"
image: "/images/logo-azul-branco-300x300.png"
baseurl: ""
social:
  twitter: https://twitter.com/vinnyfs89
  github: https://github.com/vinnyfs89
  facebook-official: https://www.facebook.com/groups/vinnyfs89/
  instagram: https://www.instagram.com/vinnyfs89
  email: viniciusfesil@gmail.com

# Build settings
markdown: kramdown

# Google-analytics
google-analytics:
  id:
plugins:
  - jekyll-paginate
paginate: 4
paginate_path: "/blog/page:num"
